baseURL: 'https://elfennol.github.io/test-hugo-blog/'
languageCode: 'en-us'
title: 'My New Hugo Site'
theme: 'github.com/adityatelange/hugo-PaperMod'

module:
    imports:
        - path: 'github.com/adityatelange/hugo-PaperMod'

menu:
    main:
        -   name: 'Categories'
            url: '/categories'
            weight: 1
        -   name: 'Tags'
            url: '/tags'
            weight: 2
